define({
    root: {
        inbox: "Inbox",
        sent: "Sent",
        trash: "Trash",
        compose: "Compose",
        markAsRead: "Mark as read",
        markAsUnread: "Mark as unread",
        deleteText: "Delete",
        from: "From",
        to: "To",
        subject: "Subject",
        message: "Message",
        date: "Date",
        newMessage: "New message",
        send: "Send",
        reply: "Reply",
        replyToAll: "Reply to all",
        forward: "Forward",
        noSubject: "(no subject)",
        emptyMessage: "(empty message)",
        re: "Re",
        fwd: "Fwd",
        forwardedMessage: "Forwarded message"
    },
    zh: true,
    en: true,
    de: true,
    es: true
});