// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.12/esri/copyright.txt for details.
//>>built
require({cache:{"dojox/html/entities":function(){define(["dojo/_base/lang"],function(z){var s=z.getObject("dojox.html.entities",!0),m=function(h,l){var m,r;if(l._encCache&&l._encCache.regexp&&l._encCache.mapper&&l.length==l._encCache.length)m=l._encCache.mapper,r=l._encCache.regexp;else{m={};r=["["];var w;for(w=0;w<l.length;w++)m[l[w][0]]="\x26"+l[w][1]+";",r.push(l[w][0]);r.push("]");r=RegExp(r.join(""),"g");l._encCache={mapper:m,regexp:r,length:l.length}}return h=h.replace(r,function(h){return m[h]})},
h=function(h,l){var m,r;if(l._decCache&&l._decCache.regexp&&l._decCache.mapper&&l.length==l._decCache.length)m=l._decCache.mapper,r=l._decCache.regexp;else{m={};r=["("];var w;for(w=0;w<l.length;w++){var s="\x26"+l[w][1]+";";w&&r.push("|");m[s]=l[w][0];r.push(s)}r.push(")");r=RegExp(r.join(""),"g");l._decCache={mapper:m,regexp:r,length:l.length}}return h=h.replace(r,function(h){return m[h]})};s.html=[["\x26","amp"],['"',"quot"],["\x3c","lt"],["\x3e","gt"],["\u00a0","nbsp"]];s.latin=[["\u00a1","iexcl"],
["\u00a2","cent"],["\u00a3","pound"],["\u20ac","euro"],["\u00a4","curren"],["\u00a5","yen"],["\u00a6","brvbar"],["\u00a7","sect"],["\u00a8","uml"],["\u00a9","copy"],["\u00aa","ordf"],["\u00ab","laquo"],["\u00ac","not"],["\u00ad","shy"],["\u00ae","reg"],["\u00af","macr"],["\u00b0","deg"],["\u00b1","plusmn"],["\u00b2","sup2"],["\u00b3","sup3"],["\u00b4","acute"],["\u00b5","micro"],["\u00b6","para"],["\u00b7","middot"],["\u00b8","cedil"],["\u00b9","sup1"],["\u00ba","ordm"],["\u00bb","raquo"],["\u00bc",
"frac14"],["\u00bd","frac12"],["\u00be","frac34"],["\u00bf","iquest"],["\u00c0","Agrave"],["\u00c1","Aacute"],["\u00c2","Acirc"],["\u00c3","Atilde"],["\u00c4","Auml"],["\u00c5","Aring"],["\u00c6","AElig"],["\u00c7","Ccedil"],["\u00c8","Egrave"],["\u00c9","Eacute"],["\u00ca","Ecirc"],["\u00cb","Euml"],["\u00cc","Igrave"],["\u00cd","Iacute"],["\u00ce","Icirc"],["\u00cf","Iuml"],["\u00d0","ETH"],["\u00d1","Ntilde"],["\u00d2","Ograve"],["\u00d3","Oacute"],["\u00d4","Ocirc"],["\u00d5","Otilde"],["\u00d6",
"Ouml"],["\u00d7","times"],["\u00d8","Oslash"],["\u00d9","Ugrave"],["\u00da","Uacute"],["\u00db","Ucirc"],["\u00dc","Uuml"],["\u00dd","Yacute"],["\u00de","THORN"],["\u00df","szlig"],["\u00e0","agrave"],["\u00e1","aacute"],["\u00e2","acirc"],["\u00e3","atilde"],["\u00e4","auml"],["\u00e5","aring"],["\u00e6","aelig"],["\u00e7","ccedil"],["\u00e8","egrave"],["\u00e9","eacute"],["\u00ea","ecirc"],["\u00eb","euml"],["\u00ec","igrave"],["\u00ed","iacute"],["\u00ee","icirc"],["\u00ef","iuml"],["\u00f0",
"eth"],["\u00f1","ntilde"],["\u00f2","ograve"],["\u00f3","oacute"],["\u00f4","ocirc"],["\u00f5","otilde"],["\u00f6","ouml"],["\u00f7","divide"],["\u00f8","oslash"],["\u00f9","ugrave"],["\u00fa","uacute"],["\u00fb","ucirc"],["\u00fc","uuml"],["\u00fd","yacute"],["\u00fe","thorn"],["\u00ff","yuml"],["\u0192","fnof"],["\u0391","Alpha"],["\u0392","Beta"],["\u0393","Gamma"],["\u0394","Delta"],["\u0395","Epsilon"],["\u0396","Zeta"],["\u0397","Eta"],["\u0398","Theta"],["\u0399","Iota"],["\u039a","Kappa"],
["\u039b","Lambda"],["\u039c","Mu"],["\u039d","Nu"],["\u039e","Xi"],["\u039f","Omicron"],["\u03a0","Pi"],["\u03a1","Rho"],["\u03a3","Sigma"],["\u03a4","Tau"],["\u03a5","Upsilon"],["\u03a6","Phi"],["\u03a7","Chi"],["\u03a8","Psi"],["\u03a9","Omega"],["\u03b1","alpha"],["\u03b2","beta"],["\u03b3","gamma"],["\u03b4","delta"],["\u03b5","epsilon"],["\u03b6","zeta"],["\u03b7","eta"],["\u03b8","theta"],["\u03b9","iota"],["\u03ba","kappa"],["\u03bb","lambda"],["\u03bc","mu"],["\u03bd","nu"],["\u03be","xi"],
["\u03bf","omicron"],["\u03c0","pi"],["\u03c1","rho"],["\u03c2","sigmaf"],["\u03c3","sigma"],["\u03c4","tau"],["\u03c5","upsilon"],["\u03c6","phi"],["\u03c7","chi"],["\u03c8","psi"],["\u03c9","omega"],["\u03d1","thetasym"],["\u03d2","upsih"],["\u03d6","piv"],["\u2022","bull"],["\u2026","hellip"],["\u2032","prime"],["\u2033","Prime"],["\u203e","oline"],["\u2044","frasl"],["\u2118","weierp"],["\u2111","image"],["\u211c","real"],["\u2122","trade"],["\u2135","alefsym"],["\u2190","larr"],["\u2191","uarr"],
["\u2192","rarr"],["\u2193","darr"],["\u2194","harr"],["\u21b5","crarr"],["\u21d0","lArr"],["\u21d1","uArr"],["\u21d2","rArr"],["\u21d3","dArr"],["\u21d4","hArr"],["\u2200","forall"],["\u2202","part"],["\u2203","exist"],["\u2205","empty"],["\u2207","nabla"],["\u2208","isin"],["\u2209","notin"],["\u220b","ni"],["\u220f","prod"],["\u2211","sum"],["\u2212","minus"],["\u2217","lowast"],["\u221a","radic"],["\u221d","prop"],["\u221e","infin"],["\u2220","ang"],["\u2227","and"],["\u2228","or"],["\u2229",
"cap"],["\u222a","cup"],["\u222b","int"],["\u2234","there4"],["\u223c","sim"],["\u2245","cong"],["\u2248","asymp"],["\u2260","ne"],["\u2261","equiv"],["\u2264","le"],["\u2265","ge"],["\u2282","sub"],["\u2283","sup"],["\u2284","nsub"],["\u2286","sube"],["\u2287","supe"],["\u2295","oplus"],["\u2297","otimes"],["\u22a5","perp"],["\u22c5","sdot"],["\u2308","lceil"],["\u2309","rceil"],["\u230a","lfloor"],["\u230b","rfloor"],["\u2329","lang"],["\u232a","rang"],["\u25ca","loz"],["\u2660","spades"],["\u2663",
"clubs"],["\u2665","hearts"],["\u2666","diams"],["\u0152","OElig"],["\u0153","oelig"],["\u0160","Scaron"],["\u0161","scaron"],["\u0178","Yuml"],["\u02c6","circ"],["\u02dc","tilde"],["\u2002","ensp"],["\u2003","emsp"],["\u2009","thinsp"],["\u200c","zwnj"],["\u200d","zwj"],["\u200e","lrm"],["\u200f","rlm"],["\u2013","ndash"],["\u2014","mdash"],["\u2018","lsquo"],["\u2019","rsquo"],["\u201a","sbquo"],["\u201c","ldquo"],["\u201d","rdquo"],["\u201e","bdquo"],["\u2020","dagger"],["\u2021","Dagger"],["\u2030",
"permil"],["\u2039","lsaquo"],["\u203a","rsaquo"]];s.encode=function(h,l){h&&(l?h=m(h,l):(h=m(h,s.html),h=m(h,s.latin)));return h};s.decode=function(m,l){m&&(l?m=h(m,l):(m=h(m,s.html),m=h(m,s.latin)));return m};return s})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/has dojo/sniff dojo/DeferredList dojo/json dojo/number dojo/dom dojo/dom-construct dojo/dom-style dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/HeatmapRenderer ../symbols/SimpleMarkerSymbol ../symbols/PictureFillSymbol ../symbols/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi dojo/i18n!dojo/cldr/nls/number".split(" "),function(z,
s,m,h,q,l,B,r,w,L,M,G,u,e,v,N,H,O,P,Q,I,J,E,C,K,F,R,S,T,U,V,W,D,X,Y,Z){var y=s([X,N],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,dotDensitySwatchSize:26,dotCoverage:75,reZeros:RegExp("\\"+Z.decimal+"0+$","g"),reZerosFractional:RegExp("(\\d)0*$","g"),_ieTimer:100,_isRightToLeft:!1,_align:null,_legendAlign:null,constructor:function(a,b){m.mixin(this,Y.widgets.legend);a=a||{};a.map?b?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=
!1===a.respectCurrentMapScale?!1:!0,this.arrangement=a.arrangement===y.ALIGN_RIGHT?y.ALIGN_RIGHT:y.ALIGN_LEFT,this.arrangement===y.ALIGN_RIGHT&&(this.alignRight=!0),this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=[]):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},postMixInProperties:function(){this.inherited(arguments);var a=["ar","he"],b,c;for(b=0;b<a.length;b+=1)c=a[b],z.locale&&
-1!==z.locale.indexOf(c)&&(-1!==z.locale.indexOf("-")?-1!==z.locale.indexOf(c+"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=this.alignRight?"left":"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},startup:function(){this.inherited(arguments);this._initialize();9>r("ie")&&(this._repaintItems=m.hitch(this,this._repaintItems),
setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(a){if(this.domNode){a?(this.layerInfos=a,this.layers=[],h.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[],
a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=this.layerInfos=null);for(a=this.domNode.children.length-1;0<=a;a--)e.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){this.layerInfos&&(this.layers=[],h.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&
(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var a=[],b=[];h.forEach(this.map.layerIds,function(c){c=this.map.getLayer(c);
var d;this._isSupportedLayerType(c)&&(c.arcgisProps&&c.arcgisProps.title&&(c._titleForLegend=c.arcgisProps.title),this.layers.push(c));"esri.layers.KMLLayer"==c.declaredClass&&(d=c.getLayers(),h.forEach(d,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==c.declaredClass&&(d=c.getFeatureLayers(),h.forEach(d,function(a){b.push(a.id)},this))},this);h.forEach(this.map.graphicsLayerIds,function(c){var d=this.map.getLayer(c);-1==h.indexOf(a,c)&&-1==h.indexOf(b,c)&&(this._isSupportedLayerType(d)&&
d._params&&d._params.drawMode)&&(d.arcgisProps&&d.arcgisProps.title&&(d._titleForLegend=d.arcgisProps.title),this.layers.push(d))},this)}this._createLegend()},_activate:function(){this._deactivate();this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=q.connect(this.map,"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=q.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=q.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=
q.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),h.forEach(this.layers,function(a){a.ovcConnect=q.connect(a,"onVisibilityChange",this,"_refreshLayers");a.oscConnect=q.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(a.odcConnect=q.connect(a,"_onDynamicLayersChange",m.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(a.oirConnect=q.connect(a,
"onRenderingChange",m.partial(this._updateImageServiceLayers,this,a)))},this))},_deactivate:function(){this._ozeConnect&&q.disconnect(this._ozeConnect);this._olaConnect&&q.disconnect(this._olaConnect);this._olroConnect&&q.disconnect(this._olroConnect);this._olrConnect&&q.disconnect(this._olrConnect);h.forEach(this.layers,function(a){a.ovcConnect&&q.disconnect(a.ovcConnect);a.oscConnect&&q.disconnect(a.oscConnect);a.odcConnect&&q.disconnect(a.odcConnect);a.oirConnect&&q.disconnect(a.oirConnect)},this)},
_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},_updateAllMapLayers:function(){this.layers=[];h.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this.layers.push(a)},this);h.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&(a._params&&a._params.drawMode)&&
this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=!1;v.set(this.domNode,"position","relative");e.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);var b=[];h.forEach(this.layers,function(c){if("esri.layers.KMLLayer"==c.declaredClass||"esri.layers.GeoRSSLayer"==c.declaredClass){var f;c.loaded?("esri.layers.KMLLayer"==c.declaredClass?f=c.getLayers():"esri.layers.GeoRSSLayer"==c.declaredClass&&(f=c.getFeatureLayers(),
c._hideLayersInLegend&&(f=h.filter(f,function(a){return-1==h.indexOf(c._hideLayersInLegend,a.id)}))),h.forEach(f,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&c._titleForLegend&&(a._titleForLegend=c._titleForLegend+" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_polygons),b.push(a))},this)):q.connect(c,"onLoad",m.hitch(this,
function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===c.declaredClass)if(c.loaded){if(c.visible&&0<c.layerInfos.length&&h.some(c.layerInfos,function(a){return a.legendURL})){var g=!1;h.forEach(c.layerInfos,function(b){b.legendURL&&-1<h.indexOf(c.visibleLayers,b.name)&&(g||(e.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(c._titleForLegend||c.name||c.id)+"\x3c/span\x3e"},this.domNode),g=!0),e.create("div",{innerHTML:"\x3cimg src\x3d'"+b.legendURL+"'/\x3e"},
this.domNode),a=!0)},this)}}else q.connect(c,"onLoad",m.hitch(this,function(){this.refresh(this.layerInfos)}));else b.push(c)},this);var c=[];h.forEach(b,function(a){if(a.loaded){if(!0===a.visible&&(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var b=e.create("div",{id:this.id+"_"+a.id,style:{display:"none"},"class":"esriLegendService"});e.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},e.create("td",{align:this._align},e.create("tr",
{},e.create("tbody",{},e.create("table",{width:"95%"},b)))));e.place(b,this.id,"first");a.legendResponse||a.renderer?this._createLegendForLayer(a):c.push(this._legendRequest(a))}}else var g=q.connect(a,"onLoad",this,function(a){q.disconnect(g);g=null;this.refresh()})},this);0===c.length&&!a?(u.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new L(c)).addCallback(m.hitch(this,function(b){a?u.byId(this.id+"_msg").innerHTML="":u.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()}))},
_createLegendForLayer:function(a){if(a.legendResponse||a.renderer){var b=!1;if(a.legendResponse){var c=a.dynamicLayerInfos||a.layerInfos;c&&c.length?h.forEach(c,function(c,f){if(!a._hideLayersInLegend||-1==h.indexOf(a._hideLayersInLegend,c.id)){var g=this._buildLegendItems(a,c,f);b=b||g}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(c=a.url?a.url.substring(a.url.lastIndexOf("/")+
1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(v.set(u.byId(this.id+"_"+a.id),"display","block"),v.set(u.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);q.connect(a,"onLoad",m.hitch(this,"_legendRequest"))},_legendRequestServer:function(a){var b=a.url,c=b.indexOf("?"),b=-1<c?b.substring(0,c)+"/legend"+b.substring(c):b+"/legend";
(c=a._getToken())&&(b+="?token\x3d"+c);var d=m.hitch(this,"_processLegendResponse"),c={f:"json"};a._params.dynamicLayers&&(c.dynamicLayers=M.stringify(this._createDynamicLayers(a)),"[{}]"===c.dynamicLayers&&(c.dynamicLayers="[]"));a._params.bandIds&&(c.bandIds=a._params.bandIds);a._params.renderingRule&&(c.renderingRule=a._params.renderingRule);return J({url:b,content:c,callbackParamName:"callback",load:function(b,c){d(a,b,c)},error:I.defaults.io.errorHandler})},_legendRequestTools:function(a){var b=
a.url.toLowerCase().indexOf("/rest/"),b=a.url.substring(0,b)+a.url.substring(b+5,a.url.length),b=this._legendUrl+"?soapUrl\x3d"+window.escape(b);if(!r("ie")||8<r("ie"))b+="\x26returnbytes\x3dtrue";var c=m.hitch(this,"_processLegendResponse");return J({url:b,content:{f:"json"},callbackParamName:"callback",load:function(b,f){c(a,b,f)},error:I.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&b.layers?(a.legendResponse=b,u.byId(this.id+"_"+a.id)&&e.empty(u.byId(this.id+"_"+a.id)),e.create("span",
{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},e.create("td",{align:this._align},e.create("tr",{},e.create("tbody",{},e.create("table",{width:"95%"},u.byId(this.id+"_"+a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+l.toJson(b))},_buildLegendItems:function(a,b,c){var d=!1,f=u.byId(this.id+"_"+a.id),g=b.parentLayerId;if(b.subLayerIds)a=e.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:{display:"none"},"class":-1==
g?0<c?"esriLegendGroupLayer":"":this._legendAlign},-1==g?f:u.byId(this.id+"_"+a.id+"_"+g+"_group")),e.create("td",{innerHTML:b.name,align:this._align},e.create("tr",{},e.create("tbody",{},e.create("table",{width:"95%","class":"esriLegendLayerLabel"},a))));else{if(a.visibleLayers&&-1==(","+a.visibleLayers+",").indexOf(","+b.id+","))return d;c=e.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:{display:"none"},"class":-1<g?this._legendAlign:""},-1==g?f:u.byId(this.id+"_"+a.id+"_"+g+"_group"));e.create("td",
{innerHTML:b.name||"",align:this._align},e.create("tr",{},e.create("tbody",{},e.create("table",{width:"95%","class":"esriLegendLayerLabel"},c))));a.legendResponse?d=d||this._buildLegendItems_Tools(a,b,c):a.renderer&&(d=d||this._buildLegendItems_Renderer(a,b,c))}return d},_buildLegendItems_Tools:function(a,b,c){var d=b.parentLayerId,f=this.map.getScale(),g=!1,n=function(a,b){var c,d;for(c=0;c<a.length;c++)if(b.dynamicLayerInfos)for(d=0;d<b.dynamicLayerInfos[d].length;d++){if(b.dynamicLayerInfos[d].mapLayerId==
a[c].layerId)return a[c]}else if(b.id==a[c].layerId)return a[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,b,f)){var t=!0;if("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISMapServiceLayer"===a.declaredClass){var p=this._getEffectiveScale(a,b);if(p.minScale&&p.minScale<f||p.maxScale&&p.maxScale>f)t=!1}if(t){var f=n(a.legendResponse.layers,b),k=f.legendType,m=f.legend;if(m){c=e.create("table",{cellpadding:0,cellspacing:0,
width:"95%","class":"esriLegendLayer"},c);var l=e.create("tbody",{},c);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b);h.forEach(m,function(c){if(!(10.1<=a.version&&!c.values&&1<m.length&&(a._hideDefaultSymbol||"\x3call other values\x3e"===c.label||!c.label&&!("esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.3<=a.version))))if(c.url&&0===c.url.indexOf("http")||c.imageData&&0<c.imageData.length)g=!0,this._buildRow_Tools(c,l,a,b.id,k)},this)}}}g&&(v.set(u.byId(this.id+"_"+
a.id+"_"+b.id),"display","block"),-1<d&&(v.set(u.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,a,d)));return g},_buildRow_Tools:function(a,b,c,d,f){var g=e.create("tr",{},b),n;this.alignRight?(b=e.create("td",{align:this._isRightToLeft?"left":"right"},g),n=e.create("td",{align:this._isRightToLeft?"left":"right",width:35},g)):(n=e.create("td",{width:35},g),b=e.create("td",{},g));g=a.url;(!r("ie")||9<=r("ie")||9>r("ie")&&"esri.layers.ArcGISImageServiceLayer"===
c.declaredClass)&&a.imageData&&0<a.imageData.length?g="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(g=c.url+"/"+d+"/images/"+a.url,(d=c._getToken())&&(g+="?token\x3d"+d));d=e.create("img",{src:g,border:0,style:"opacity:"+c.opacity},n);a=e.create("td",{innerHTML:a.label,align:this._align},e.create("tr",{},e.create("tbody",{},e.create("table",{width:"95%",dir:"ltr"},b))));f&&("Stretched"===f&&10.3<=c.version&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass)&&(a.style.verticalAlign=
"top",a.style.lineHeight="1",d.style.marginBottom="-1px",d.style.display="block",b.style.verticalAlign="top");9>r("ie")&&(d.style.filter="alpha(opacity\x3d"+100*c.opacity+")")},_getVariable:function(a,b){return a?a[b]||h.filter(a.visualVariables,function(a){return a.type===b})[0]:null},_buildLegendItems_Renderer:function(a,b,c){var d=b.parentLayerId,f=this.map,g=f.getScale(),n=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,g)){var t,p,k=a.renderer,l,A,x,r,q;if(k instanceof R&&(k=(k=
"zoom"===k.rangeType?k.getRendererInfoByZoom(f.getZoom()):k.getRendererInfoByScale(g))&&k.renderer,!k))return!1;var f=this._getVariable(k,"colorInfo"),g=this._getVariable(k,"opacityInfo"),s=this._getVariable(k,"sizeInfo");f?(l=this._getMedianColor(k,f),f.field&&(x=m.isFunction(f.field)?null:a._getField(f.field,!0))):g&&(q=m.isFunction(g.field)?null:a._getField(g.field,!0));s&&s.field&&(r=m.isFunction(s.field)?null:a._getField(s.field,!0));if(k instanceof U)n=!0,this._showHeatRamp(a,b,k,c);else if(k instanceof
S)n=!0,this._showDotDensityLegend(a,b,k,c);else if(k instanceof T)n=!0,p=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),t=e.create("tbody",{},p),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(p,a,b),k.latestObservationRenderer&&k.latestObservationRenderer instanceof C&&this._buildRow_Renderer(a,k.latestObservationRenderer.symbol,l,k.latestObservationRenderer.label||this.NLS_currentObservations,null,t),k.observationRenderer&&k.observationRenderer instanceof
C&&this._buildRow_Renderer(a,k.observationRenderer.symbol,l,k.observationRenderer.label||this.NLS_previousObservations,null,t);else if(k instanceof K){if(k.infos&&0<k.infos.length){n=!0;p=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);t=e.create("tbody",{},p);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(p,a,b);var w=[];h.forEach(k.infos,function(b){var c=null;a._editable&&a.types&&(c=this._getTemplateFromTypes(a.types,b.value));var d=b.label;null==
d&&(d=b.value);-1===h.indexOf(w,d)&&(w.push(d),this._buildRow_Renderer(a,b.symbol,l,d,c,t))},this)}}else k instanceof F?k.infos&&0<k.infos.length&&(n=!0,p=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),t=e.create("tbody",{},p),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(p,a,b),h.forEach(k.infos,function(b){var c=b.label;null==c&&(c=b.minValue+" - "+b.maxValue);this._buildRow_Renderer(a,b.symbol,l,c,null,t)},this)):k instanceof C&&(n=!0,p=e.create("table",
{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),t=e.create("tbody",{},p),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(p,a,b),A=null,a._editable&&(a.templates&&0<a.templates.length)&&(A=a.templates[0]),p=(x||q)&&r?null:x||q||r,this._buildRow_Renderer(a,k.symbol,l,p?p.alias||p.name:k.label,A,t),A=k.symbol&&k.symbol.color,p&&(x=q=r=null));n&&(f&&f.field?(x&&this._isSmartRenderer(k,x.name)&&(x=null),this._showColorRamp(a,b,k,null,c,f,x)):g&&A&&this._showColorRamp(a,
b,k,A,c,g,q),s&&s.field&&(r&&this._isSmartRenderer(k,r.name)&&(r=null),this._showSizeLegend(a,b,k,s,l,c,r)));!a._hideDefaultSymbol&&k.defaultSymbol&&(n=!0,p=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),t=e.create("tbody",{},p),this._buildRow_Renderer(a,k.defaultSymbol,null,k.defaultLabel||"others",null,t))}n&&(v.set(u.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<d&&(v.set(u.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,
d)));return n},_isSmartRenderer:function(a,b){return a instanceof F&&a.infos&&1===a.infos.length&&a.attributeField===b},_showColorRamp:function(a,b,c,d,f,g,n){var t;t=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f);f=e.create("tbody",{},t);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(t,a,b);n&&this._addSubHeader(f,n.alias||n.name);b=this._getRampStops(c,g,d);b.length&&this._drawColorRamp(f,b,a)},_getMedianColor:function(a,b){var c,d;b.colors?(c=
b.minDataValue,d=b.maxDataValue):b.stops&&(c=b.stops[0].value,d=b.stops[b.stops.length-1].value);return a.getColor(c+(d-c)/2,{colorInfo:b})},_getRampStops:function(a,b,c){var d,f,g,n,e=!1;b.colors||b.opacityValues?(f=b.maxDataValue-b.minDataValue,d=h.map([0,0.25,0.5,0.75,1],function(a){g=b.minDataValue+a*f;return Number(g.toFixed(6))}),this._checkPrecision(0,4,d)):b.stops&&(d=h.map(b.stops,function(a){return a.value}),(e=h.some(b.stops,function(a){return!!a.label}))&&(n=h.map(b.stops,function(a){return a.label})));
var p=d[0],k,m,l;f=d[d.length-1]-p;return h.map(d,function(g,h){c?(k=new B(c.toRgba()),m=a.getOpacity(g,{opacityInfo:b}),null!=m&&(k.a=m)):k=a.getColor(g,{colorInfo:b});l="";0===h?l="\u2264 ":h===d.length-1&&(l="\u2265 ");return{value:g,color:k,offset:1-(g-p)/f,label:e?n[h]:l+G.format(g,{places:20,round:-1}).replace(this.reZerosFractional,"$1").replace(this.reZeros,"")}},this).reverse()},_checkPrecision:function(a,b,c){var d=a+(b-a)/2,f=c[a],g=c[d],n=c[b],e=Math.floor(f),h=Math.floor(g),k=Math.floor(n);
e===f&&(k===n&&h!==g&&e!==h&&k!==h)&&(c[d]=h);a+1!==d&&this._checkPrecision(a,d,c);d+1!==b&&this._checkPrecision(d,b,c)},_drawColorRamp:function(a,b,c){var d=e.create("tr",{},a),f,g,n,t,p,k,m;this.alignRight?(a=e.create("td",{align:this._isRightToLeft?"left":"right"},d),f=e.create("td",{align:this._isRightToLeft?"left":"right",width:34},d)):(f=e.create("td",{width:34,align:"center"},d),a=e.create("td",{},d));g=e.create("div",{style:"position: relative; width:34px;"},f);n=e.create("div",{"class":"esriLegendColorRamp"},
g);d=v.get(n,"width");f=v.get(n,"height");v.set(g,"height",f+"px");n=H.createSurface(n,d,f);9>r("ie")&&(p=n.getEventSource(),v.set(p,"position","relative"),v.set(p.parentNode,"position","relative"));try{k=n.createRect({width:d,height:f}),k.setFill({type:"linear",x1:0,y1:0,x2:0,y2:f,colors:b}).setStroke(null),n.createRect({width:d,height:f}).setFill(new B([255,255,255,1-c.opacity])).setStroke(null),this._surfaceItems.push(n)}catch(l){n.clear(),n.destroy()}t=e.create("div",{"class":"esriLegendColorRampLabels"},
a);h.forEach(b,function(a,c){a.label&&(m="top:"+100*a.offset+"%;",e.create("div",{"class":"esriLegendColorRampTick"+(c===b.length-1?" esriLegendColorRampTickLast":""),innerHTML:"\x26nbsp;",style:m},g),e.create("div",{"class":"esriLegendColorRampLabel",innerHTML:a.label,style:m},t))})},_showHeatRamp:function(a,b,c,d){var f,g=c.field;f=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);d=e.create("tbody",{},f);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(f,
a,b);(g=g&&a.getField(g))&&this._addSubHeader(d,g.alias||g.name);b=this._getHeatmapStops(c);b.length&&this._drawColorRamp(d,b,a)},_getHeatmapStops:function(a){var b=a.colorStops;a=a.colors;var c,d,f,g;if(b&&b[0])if(c=b.length-1,a=b[0]&&null!=b[0].ratio){if((a=b[c])&&1!==a.ratio)b=b.slice(0),b.push({ratio:1,color:a.color}),c++}else d=b[0].value,f=b[c].value-d,b=h.map(b,function(a){return{color:a.color,ratio:(a.value-d)/f}});else a&&a[0]&&(c=a.length-1,g=1/(a.length-1),b=h.map(a,function(a,b){return{color:a,
ratio:b*g}}));b=h.map(b,function(a,b){var d="";0===b?d="Low":b===c&&(d="High");return{color:a.color,label:d,offset:1-a.ratio}});return b.reverse()},_showDotDensityLegend:function(a,b,c,d){var f=c.legendOptions,g,n,t,p,k,l,r,q=this.dotDensitySwatchSize,s=Math.round(q/2);f&&(n=f.backgroundColor,t=f.outline,p=f.valueUnit,k=f.dotCoverage);k=(k||this.dotCoverage)/100;r=Math.round(q*q/Math.pow(c.dotSize,2)*k);d=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);l=e.create("tbody",
{},d);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(d,a,b);this._addSubHeader(l,E.substitute({value:c.dotValue,unit:p||""},this.NLS_dotValue));h.forEach(c.fields,function(b){b=m.mixin({},b);b.numPoints=r;g=new W(c._generateImageSrc(q,q,[b],{x:0,y:0},{x:q,y:q},n),t||c.outline,q,q);b=a._getField(b.name,!0)||b;this._buildRow_Renderer(a,g,null,b.alias||b.name,null,l,{type:"path",path:"M "+-s+","+-s+" L "+s+","+-s+" L "+s+","+s+" L "+-s+","+s+" L "+-s+","+-s+" E"})},this)},_showSizeLegend:function(a,
b,c,d,f,g,n){var t=d.legendOptions,t=t&&t.customValues,p,k=d.minDataValue,m=d.maxDataValue,l=this._getSizeSymbol(c,f);"unknown"!==d.valueUnit||(!l||!t&&(null==k||null==m))||(f=e.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g),p=e.create("tbody",{},f),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(f,a,b),n&&this._addSubHeader(p,n.alias||n.name),b=t||this._getDataValues(k,m),h.forEach(b,function(b){l=D.fromJson(l.toJson());this._applySize(l,c,d,b);b=G.format(b,
{places:20,round:-1}).replace(this.reZerosFractional,"$1").replace(this.reZeros,"");this._buildRow_Renderer(a,l,null,b,null,p)},this))},_getSizeSymbol:function(a,b){var c,d;if(a instanceof C)d=!0,c=a.symbol;else if(a instanceof K||a instanceof F)c=a.infos[0].symbol;if(c=-1!==c.type.indexOf("fillsymbol")?null:c)!d&&"picturemarkersymbol"===c.type?(c=new V,c.setStyle("square"),c.outline.setWidth(1)):c=D.fromJson(c.toJson()),b?c.setColor(new B(b.toRgba())):d||c.setColor(new B([127,127,127]));return c},
_applySize:function(a,b,c,d){var f=a.type;c={sizeInfo:c,shape:-1!==f.indexOf("markersymbol")?a.style:null};b=b.getSize(d,c);switch(f){case "simplemarkersymbol":a.setSize(b);break;case "picturemarkersymbol":a.setWidth(b);a.setHeight(b);break;case "simplelinesymbol":case "cartographiclinesymbol":a.setWidth(b)}},_getDataValues:function(a,b){var c=[a,b],d=Math.LN10,f=Math.log(a),g=Math.log(b),e,t,p,k,m;h.forEach([1,2.5,5],function(a){k=Math.log(a);e=Math.ceil((f-k)/d);t=Math.floor((g-k)/d);if(!(Infinity===
Math.abs(e)||Infinity===Math.abs(t)))for(p=e;p<t+1;p++)m=a*Math.pow(10,p),-1===h.indexOf(c,m)&&c.push(m)});c.sort(this._sorter);return c.reverse()},_sorter:function(a,b){return a-b},_buildRow_Renderer:function(a,b,c,d,f,g,n){var h=e.create("tr",{},g),m;this.alignRight?(g=e.create("td",{align:this._isRightToLeft?"left":"right"},h),m=e.create("td",{align:this._isRightToLeft?"left":"right",width:35},h)):(m=e.create("td",{width:35,align:"center"},h),g=e.create("td",{},h));var k=h=30;"simplemarkersymbol"==
b.type?(h=Math.min(Math.max(h,b.size+12),125),k=Math.min(Math.max(k,b.size+12),125)):"picturemarkersymbol"==b.type&&(h=Math.min(Math.max(h,b.width),125),k=Math.min(b.height||k,125));m=e.create("div",{style:"width:"+h+"px;height:"+k+"px;"},m);E.isDefined(d)&&"number"===typeof d&&(d=""+d);e.create("td",{innerHTML:d||"",align:this._align},e.create("tr",{},e.create("tbody",{},e.create("table",{width:"95%"},g))));a=this._drawSymbol(m,b,c,h,k,f,a,n);this._surfaceItems.push(a)},_addSubHeader:function(a,
b){var c=e.create("tr",{},a),c=e.create("td",{align:this._align,colspan:2},c);e.create("td",{innerHTML:b||"",align:this._align},e.create("tr",{},e.create("tbody",{},e.create("table",{width:"95%"},c))))},_drawSymbol:function(a,b,c,d,f,g,e,h){b=D.fromJson(b.toJson());var l=e.opacity;c&&b.setColor(new B(c.toRgba()));if("simplelinesymbol"===b.type||"cartographiclinesymbol"===b.type||"textsymbol"===b.type){if(!b.color)return;c=b.color.toRgba();c[3]*=l;b.color.setColor(c)}else if("simplemarkersymbol"===
b.type||"simplefillsymbol"===b.type){if(!b.color)return;c=b.color.toRgba();c[3]*=l;b.color.setColor(c);b.outline&&b.outline.color&&(c=b.outline.color.toRgba(),c[3]*=l,b.outline.color.setColor(c))}else"picturemarkersymbol"===b.type&&(a.style.opacity=l,a.style.filter="alpha(opacity\x3d("+100*l+"))");a=H.createSurface(a,d,f);9>r("ie")&&(c=a.getEventSource(),v.set(c,"position","relative"),v.set(c.parentNode,"position","relative"));g=this._getDrawingToolShape(b,g)||D.getShapeDescriptors(b);var k;try{k=
a.createShape(h||g.defaultShape).setFill(g.fill).setStroke(g.stroke)}catch(q){a.clear();a.destroy();return}var s=k.getBoundingBox();h=s.width;g=s.height;var l=-(s.x+h/2),u=-(s.y+g/2);c=a.getDimensions();l={dx:l+c.width/2,dy:u+c.height/2};if("simplemarkersymbol"===b.type&&"path"===b.style)d=e._getScaleMatrix(s,b.size),k.applyTransform(O.scaleAt(d.xx,d.yy,{x:c.width/2,y:c.height/2}));else if(h>d||g>f)e=h/d>g/f,d=((e?d:f)-5)/(e?h:g),m.mixin(l,{xx:d,yy:d});k.applyTransform(l);return a},_getDrawingToolShape:function(a,
b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 E"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 E"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 E"};break;case "esriFeatureEditToolCircle":c={type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",
cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){h.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&m.isArray(a.children)&&h.forEach(a.children,this._repaint,this)}},_createHoverAction:function(a,b,c){var d=b._hoverLabel||b._hoverLabels[c.id];d&&(b.mouseMoveHandler=
b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=q.connect(a,"onmousemove",m.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,v.set(u.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(m.hitch(this,function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=!0,u.byId(this.id+"_hoverLabel")){var d=u.byId(this.id+"_hoverLabel");d.innerHTML="\x3cspan\x3e"+c+"\x3c/span\x3e";v.set(d,"top",
b+"px");v.set(d,"left",a+15+"px");v.set(d,"display","")}else e.create("div",{innerHTML:"\x3cspan\x3e"+c+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},d)),b.mouseOutHandler=b.mouseOutHandler||{},b.mouseOutHandler[c.id]=q.connect(a,"onmouseout",m.hitch(this,function(a){this.mouseY=this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,v.set(u.byId(this.id+"_hoverLabel"),"display","none"))})))},
_removeHoverHandlers:function(){var a;h.forEach(this.layers,function(b){if(b.mouseMoveHandler)for(a in b.mouseMoveHandler)q.disconnect(b.mouseMoveHandler[a]);if(b.mouseOutHandler)for(a in b.mouseOutHandler)q.disconnect(b.mouseOutHandler[a])})},_createDynamicLayers:function(a){var b=[],c;h.forEach(a.dynamicLayerInfos||a.layerInfos,function(d){c={id:d.id};c.source=d.source&&d.source.toJson();var f;a.layerDefinitions&&a.layerDefinitions[d.id]&&(f=a.layerDefinitions[d.id]);f&&(c.definitionExpression=
f);var g;a.layerDrawingOptions&&a.layerDrawingOptions[d.id]&&(g=a.layerDrawingOptions[d.id]);g&&(c.drawingInfo=g.toJson());c.minScale=d.minScale||0;c.maxScale=d.maxScale||0;b.push(c)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var d,f=b.dynamicLayerInfos||b.layerInfos;for(d=0;d<f.length;d++)if(c==f[d].id){-1<f[d].parentLayerId&&(v.set(u.byId(this.id+
"_"+a+"_"+f[d].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,f[d].parentLayerId));break}},_addSubLayersToHide:function(a){function b(c,d){var f=a.layer.dynamicLayerInfos||a.layer.layerInfos,g,e;for(g=0;g<f.length;g++)if(f[g].id===c&&f[g].subLayerIds)for(e=0;e<f[g].subLayerIds.length;e++){var l=f[g].subLayerIds[e];-1===h.indexOf(d,l)&&(d.push(l),b(l,d))}}a.layer.layerInfos&&h.forEach(a.layer._hideLayersInLegend,function(c){b(c,a.layer._hideLayersInLegend)})},_isLayerInScale:function(a,
b,c){var d,f=!0;if(a.legendResponse&&a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var g=a.legendResponse.layers[d];if(b.id==g.layerId){var e,h;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==g.minScale&&a.tileInfo&&(e=a.tileInfo.lods[0].scale),0==g.maxScale&&a.tileInfo&&(h=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(e=Math.min(a.minScale,g.minScale)||a.minScale||g.minScale,h=Math.max(a.maxScale,g.maxScale));if(0<e&&e<c||h>c)f=!1;break}}else if(a.minScale||
a.maxScale)if(a.minScale&&a.minScale<c||a.maxScale&&a.maxScale>c)f=!1;return f},_getServiceTitle:function(a){var b=a._titleForLegend;b||((b=a.url)?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+
1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));return P.encode(b)},_getEffectiveScale:function(a,b){var c=b.minScale,d=b.maxScale;if(E.isDefined(b.parentLayerId)){var f=a.layerInfos,g=b.parentLayerId,e;for(e=f.length-1;0<=e;e--)if(f[e].id==g)if(0==c&&0<f[e].minScale?c=f[e].minScale:0<c&&0==f[e].minScale||0<c&&0<f[e].minScale&&(c=Math.min(c,f[e].minScale)),d=Math.max(d||0,f[e].maxScale||0),-1<f[e].parentLayerId)g=f[e].parentLayerId;else break}return{minScale:c,maxScale:d}},_isSupportedLayerType:function(a){return a&&
("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1}});m.mixin(y,{ALIGN_LEFT:0,ALIGN_RIGHT:1});
r("extend-esri")&&m.setObject("dijit.Legend",y,Q);return y});